### ISSUE TITLE
文字颜色和文字背景颜色调色板需二次点击

### ISSUE THREAD

**Issue by GhostyCHEN** [KID-1912/vue-tiptap-appmsg-editor#1]
当焦点在编辑区域中时，点击文字颜色或者文字背景颜色，调色板会闪退，需再次点击才出现

**Comment by KID-1912** [comment]
已修复 [A commit](https://github.com/KID-1912/vue-tiptap-appmsg-editor/commit/fa2656a790069451575868e71aebad5d387c3c0c)
