### ISSUE TITLE
正文字数、预览和一键复制功能无效

### ISSUE THREAD

**Issue by gaohanss** [KID-1912/vue-tiptap-appmsg-editor#2]
项目发布后，正文字数、预览和一键复制功能没响应不知道是什么原因，非vue版本的正常

**Comment by KID-1912** [comment]
已将非vue版本上述功能迁移到当前项目 [feat:补充迁移“字数统计”、“一键复制”](https://github.com/KID-1912/vue-tiptap-appmsg-editor/commit/c72fbbf5525876d23f2cc02518bbe1abfc7b620a)
